### ISSUE TITLE
Add support for passing CSS animation classes as named arguments

### ISSUE THREAD

**Issue by illyabusigin** [peec/ember-css-transitions#35]
It would be great if we could pass our CSS animation classes as named arguments like so:
```hbs
<div
  {{css-transition
    enter="opacity-0"
    enterActive="ease-out duration-200 opacity-100"
    leave="opacity-100"
    leaveActive="opacity-0 ease-in duration-200"
  }}
>
...
</div>
```
I build many of my apps with [TailwindCSS](https://tailwindcss.com) and this would be incredibly helpful :)

**Comment by miguelcobain** [comment]
This is a great idea. Plays really well with TailwindCSS, indeed. Especially now that it has animations built in. Definitely want this supported.

**Comment by miguelcobain** [comment]
The problem is that we want to support the animation of adding and removing classes, which api is very similar:

From: http://peec.github.io/ember-css-transitions/docs/add-removal
```hbs
<div {{css-transition isImportant=this.isImportant}}>
  <h1>A very important text.</h1>
</div>
```

So, in your example, if someone wanted to animate the add/removal of the `"enter"` class, it would be ambiguous.

We might need to rethink the API for this a bit.

**Comment by miguelcobain** [comment]
One idea is to have the positional argument be either a hash or a string. If a string, then we infer the class names as we already do. Optionally the user can pass in a hash with the class names customized:
```hbs
<div
  {{css-transition (hash
    enter="opacity-0"
    enterActive="ease-out duration-200 opacity-100"
    leave="opacity-100"
    leaveActive="opacity-0 ease-in duration-200"
  )}}
>
  ...
</div>
```

This even allows the possibility to compose things like

```hbs
<div {{css-transition this.fadeIn}}>
  ...
</div>
```

where `this.fadeIn` is an object defined elsewhere, or it could even come from a helper.

Class adds/removals could stay untouched.

**Comment by illyabusigin** [comment]
I like the idea of composition here with the positional argument. I actually went ahead and implemented my original request in a private repo. I'll fork and publish a link here for reference.

**Comment by pdud** [comment]
Thank you very much for this awesome addon and thanks for being open to supporting this! Thanks for creating the issue @illyabusigin 

I was also inspired to see this added because of Tailwind.css.

In a [Conference talk from Adam Wathan of Tailwind on Best Practices at around 23m](https://youtu.be/J_7_mnFSLDg?t=1418) he shows how he uses Vue to leverage this functionality. This led me to check out Vue's documentation on transition.

https://vuejs.org/v2/guide/transitions.html#Transition-Classes

I'd imagine we could gain a lot if we leaned on an interface of something core to Vue.

**I've not used Vue and I don't know how feasible these breaking change suggestions are 😬. I'd be interested in talking about it more and helping where possible. Thanks again!**

### Transition Classes ([reference](https://vuejs.org/v2/guide/transitions.html#Transition-Classes))

- Vue supports something like ember-css-transitions currently does `<div {{css-transition "example"}}></div>` via `<transition name="example"></transition>`
- Vue has 6 classes (`v-enter`, `v-enter-active`, `v-enter-to`, `v-leave`, `v-leave-active`, `v-leave-to`)
- The two classes (`v-enter-to` and `v-leave-to`) were added in more recent versions of Vue
- Vue mentions the ease of usage of their format with https://daneden.github.io/animate.css/ and other existing css libraries 

```hbs
<div
  {{css-transition
    enterClass="opacity-0"
    enterActiveClass="ease-out duration-200"
    enterToClass="opacity-100"
    leaveClass="opacity-100"
    leaveActiveClass="ease-in duration-200"
    leaveToClass="opacity-0"
  }}
>
...
</div>
```

### Animating class add/removal

As mentioned here https://github.com/peec/ember-css-transitions/issues/35#issuecomment-614992678

I believe this could be supported if it were a key `name`?

```hbs
<div {{css-transition name=(if isImportant ? "important" "not-important")}}>
...
</div>

{{!-- or --}}

<div {{css-transition name=(if isImportant ? "important")}}>
...
</div>
```

Another option

```hbs
<div
  {{css-transition
    name="is-important"
    if=this.isImportant
  }}
>
...
</div>
```

Or in the verbose format (I suppose it needs if)

```hbs
<div
  {{css-transition
    enterClass="opacity-0"
    enterActiveClass="ease-out duration-200"
    enterToClass="opacity-100"
    leaveClass="opacity-100"
    leaveActiveClass="ease-in duration-200"
    leaveToClass="opacity-0"
    if=this.isImportant
  }}
>
...
</div>
```

### On the positional argument composablilty

I do like that too.

We could also extract components? (Tailwind makes me extract a lot of template only components 😅)

```hbs
<FadeTransition>
  ...
</FadeTransition>
```

### Javascript Hooks

Vue also has javascript hooks ([reference](https://vuejs.org/v2/guide/transitions.html#JavaScript-Hooks))

> These hooks can be used in combination with CSS transitions/animations or on their own.

```hbs
<div
  {{css-transition
    onBeforeEnter=this.onBeforeEnter
    onEnter=this.onEnter
    onAfterEnter=this.onAfterEnter
    onEnterCancelled=this.onEnterCancelled
    onBeforeLeave=this.onBeforeLeave
    onLeave=this.onLeave
    onAfterLeave=this.onAfterLeave
    onLeaveCancelled=this.onLeaveCancelled
  }}
>
...
</div>
```

**Comment by pdud** [comment]
Hi @miguelcobain and @illyabusigin

I’ve just added 3 draft PRs for your consideration each applying different techniques to support the add-on as is the best as possible and supporting multiple animation classes.

I’d happily do any work needed to get the one you prefer over the finish line. I don’t have a strong preference between 2 and 3 but would imagine 2 is more in line with the original intentions of the add on.

### 1. Mimic reactjs/react-transition-group v1

[Pull Request](https://github.com/peec/ember-css-transitions/pull/36)

This is what ember-css-transitions links to as the main inspiration for this add-on. The version they are referring to in the React docs is actually v1.

This branch attempts to support passing in a hash of class names as mentioned here: https://github.com/peec/ember-css-transitions/issues/35#issuecomment-614995716

Unfortunately this won’t work for Tailwind, Animate.css users. Due to both enter/ enterActive (or leave/leaveActive) classes being applied the latest class in the stylesheet will show. So in my PR fade-in works but fade-out does not.

### 2. Mimic reactjs/react-transition-group v4 (latest) 

[Pull Request](https://github.com/peec/ember-css-transitions/pull/37)

This is the same React library’s latest version. They have changed to an approach that will work but does result in a breaking change.

The breaking change is ember-css-transition users are going to have to update their css. The difference is enter is added, then removed and enterActive is added.


### 3. Mimic Vue’s transitions

[Pull Request](https://github.com/peec/ember-css-transitions/pull/38)

This is very similar to option 2.

It’s also a breaking change for current ember-css-transition users in the exact same way for the exact same reasons.

The difference is in using positional arguments (transition name or hash) vs named arguments (name, enter, enterActive, leave, leaveActive)

## Other

- Animating class add/ removal would work with any of them. I’m not sure it’s needed when using manual classes.
- I swapped to max-height rather than height for a smoother transition in the demo :)
