### ISSUE TITLE
Watching CSS classes

### ISSUE THREAD

**Issue by knownasilya** [peec/ember-css-transitions#5]
So the current mixin helps with rendering and tearing down, but there is no way to watch classes and their transition times to do `.my-class-add` when a class was added or `.my-class-remove` when removed along with an active state for each. 

I think this needs a need mixin.

**Comment by knownasilya** [comment]
Seems like we could build of the `classNameBindings` array. I think this would only work with single class bindings, like 'isClosed' or 'closed:is-closed'. 

Could be explicit by providing an array of watched properties: `watchedProperties`

**Comment by miguelcobain** [comment]
@knownasilya So, this is the missing functionality, right: https://docs.angularjs.org/guide/animations#class-and-ngclass-animation-hooks?

In your example, the following would happen:
- on a transition from `false` to `true`
  1. adds `is-closed-add`, `is-closed` and `is-closed-add-active` (maybe we can't add them all at once, right?)
  2. removes `is-closed-add` and `is-closed-add-active` when transition ends (again, can we remove both at once)
- on a transition from `true` to `false` (has the class `is-closed`)
  1. adds `is-closed-remove` (maybe we can't add them all at once, right?)
  2. remove `is-closed`
  3. add `is-closed-remove-active`
  4. remove `is-closed-remove` and `is-closed-remove-active`

I'm still not sure of the timings to do this, etc. This seems a bit more easier in principle than the teardown, setup part already done, since we don't have to deal with clones, for example.

**Comment by knownasilya** [comment]
Yeah, the only thing I'm unsure about is the timing.. Lol

**Comment by miguelcobain** [comment]
That should be similar to the existing -enter, -enter-active, -leave and -leave-active.
`-enter` - `-add`
`-enter-active` - `-add-active`
`-remove` - `-leave`

**Comment by miguelcobain** [comment]
This should be implemented in 0.1.5.
